version: "3.9"

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    depends_on:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
