version: "3.9"

services:
  backend:
    build:
      context: ./server
      dockerfile: ../docker/server.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env

  frontend:
    build:
      context: ./client
      dockerfile: ../docker/client.Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
